networks:
  management:
    name: management
    external: true

services:
  # Watchtower - auto updater
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  # Container management
  portainer: # https://github.com/portainer/portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vols/portainer/data:/data
    restart: always
    networks:
      management:
        ipv4_address: ${PORTAINER_IP}
