networks:
  quinly-services:
    name: quinly-services
    external: true
  patroni-cluster:
    driver: bridge

services:
  etcd1:
    image: ${ETCD_IMAGE}
    container_name: etcd1
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcdnode_data1:/etcd-data
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_NAME: etcd1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${ETCD1_IP}:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://${ETCD1_IP}:2379
      # ETCD_INITIAL_CLUSTER: etcdnode01=http://etcdnode01:2380,etcdnode02=http://${ETCD2_IP}:2380
      ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN}
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 2381:2379
      - 2382:2380
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${ETCD1_IP}

  etcd2:
    image: ${ETCD_IMAGE}
    container_name: etcd2
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcdnode_data2:/etcd-data
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_NAME: etcd2
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${ETCD2_IP}:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://${ETCD2_IP}:2379
      ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN}
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 2383:2379
      - 2384:2380
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${ETCD2_IP}

  etcd3:
    image: ${ETCD_IMAGE}
    container_name: etcd3
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcdnode_data3:/etcd-data
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_NAME: etcd3
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://${ETCD3_IP}:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://${ETCD3_IP}:2379
      ETCD_INITIAL_CLUSTER: ${ETCD_INITIAL_CLUSTER}
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN}
      ETCD_INITIAL_CLUSTER_STATE: new
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${ETCD3_IP}

  patroni1:
    container_name: patroni1
    build:
      dockerfile: ./patroni.dockerfile
      context: .
      target: postgres-patroni
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - postgres_data1:/var/lib/postgresql/data
      - ./patroni1.yml:/venv/etc/patroni.yml
    ports:
      - 5432:5432
      - 8008:8008
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${PATRONI1_IP}
    depends_on:
      - etcd1

  patroni2:
    container_name: patroni2
    build:
      dockerfile: ./patroni.dockerfile
      context: .
      target: postgres-patroni
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./patroni2.yml:/venv/etc/patroni.yml
    ports:
      - 5433:5432
      - 8009:8008
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${PATRONI2_IP}
    depends_on:
      - etcd2

  patroni3:
    container_name: patroni3
    build:
      dockerfile: ./patroni.dockerfile
      context: .
      target: postgres-patroni
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - postgres_data3:/var/lib/postgresql/data
      - ./patroni3.yml:/venv/etc/patroni.yml
    ports:
      - 5434:5432
      - 8010:8008
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${PATRONI3_IP}
    depends_on:
      - etcd3

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "5000:5000" # Expose HAProxy on port 5000
    networks:
      patroni-cluster:
      quinly-services:
        ipv4_address: ${HA_PROXY_IP}

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
  etcdnode_data1:
  etcdnode_data2:
  etcdnode_data3:
