networks:
  quinly-services:
    external: true
    
services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      FTLCONF_misc_etc_dnsmasq_d: "true"
    # Volumes store your data between container upgrades
    volumes:
      - pihole-etc:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.
      - ./02-quinly-wildcard-dns.conf:/etc/dnsmasq.d/02-quinly-wildcard-dns.conf
      #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      #cap_add:
      #- NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    ports:
      - 53:53
    networks:
      quinly-services:
        ipv4_address: ${IP_ADDRESS}
    
volumes:
  pihole-etc:
  pihole-dnsmasq: